import { AuthProvider } from "@/context/AuthContext"
import '../styles/global.css';
//import './global.css';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       
      <body><AuthProvider>{children}</AuthProvider></body>
    </html>
  )
}
