import { AuthProvider } from "@/context/AuthContext"
import '../styles/global.css';
import { ProjectProvider } from "@/context/ProjectContext";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
  params: { projectId } 
}: {
  children: React.ReactNode
  params: { projectId: string };
}) {
  return (
    <html lang="en">
      <body>
      <AuthProvider>
          <ProjectProvider projectId={projectId}>{children}</ProjectProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
